In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
b = np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
print(c[1][1])

5


In [16]:
a = np.zeros((3,3))
print(a)
print(type(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [17]:
b = np.ones((3,3))

In [18]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
c = np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
d = np.eye(4)
print(d)
# identity matrix - square size matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
e = np.random.random((2,3))
print(e)

[[0.1311735  0.21901136 0.90932002]
 [0.57748489 0.23502396 0.70220583]]


In [26]:
print(e[:,1:3])

[[0.21901136 0.90932002]
 [0.23502396 0.70220583]]


In [29]:
e[1, 1:] = 1
print(e)

[[0.1311735  0.21901136 0.90932002]
 [0.57748489 1.         1.        ]]


In [38]:
z = np.zeros((3,3), dtype = np.int64)
print(z)
z[1,:]= 3
z[:,-1]= 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [39]:
print(z.dtype)

int64


In [41]:
# Mathematical OPeratiom 
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])
print(x+y)
print(np.add(x,y))

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]


In [42]:
print(x-y)
print(np.subtract(x,y))

[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]


In [44]:
print(x*y)
print(np.multiply(x,y))

[[ 4 10]
 [18 28]]
[[ 4 10]
 [18 28]]


In [46]:
print(x/y)
print(np.divide(x,y))

[[0.25       0.4       ]
 [0.5        0.57142857]]
[[0.25       0.4       ]
 [0.5        0.57142857]]


In [47]:
print(x**0.5)
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [48]:
# Matrix Multiplication or Dot Product 
print(x.dot(y))
print(np.dot(x,y))

[[16 19]
 [36 43]]
[[16 19]
 [36 43]]


In [49]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [50]:
print(a)
print(sum(a))
print(max(a))

[1 2 3 4]
10
4


In [51]:
print(x)

[[1 2]
 [3 4]]


In [53]:
print(np.sum(x))

10


In [55]:
print(np.sum(x, axis = 0))

[4 6]


In [58]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [62]:
a= np.stack((a,b), axis = 0)
# print(np.stack((a,b),axis = 1))

ValueError: all input arrays must have the same shape

In [63]:
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


In [78]:
a = a.reshape((-1,1))

In [79]:
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [16]
 [36]
 [64]]


In [80]:
c = np.random.random((2,3))

In [81]:
print(c)

[[0.44073528 0.01181787 0.58016226]
 [0.12889604 0.25829962 0.31563829]]


In [91]:
a = np.arange(10) +5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [94]:
np.random.shuffle(a)

In [95]:
print(a)

[ 7 14  6 13 12 11  9  5  8 10]


In [102]:
# Returns values from random normal distribution
a = np.random.randn(2,3)
print(a)

[[-0.11058748  0.3873377   1.57600733]
 [ 0.72036542 -0.42368207 -0.57524999]]
