In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
b = np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
print(c[1][1])

5


In [16]:
a = np.zeros((3,3))
print(a)
print(type(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [17]:
b = np.ones((3,3))

In [18]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
c = np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
d = np.eye(4)
print(d)
# identity matrix - square size matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
e = np.random.random((2,3))
print(e)

[[0.1311735  0.21901136 0.90932002]
 [0.57748489 0.23502396 0.70220583]]


In [26]:
print(e[:,1:3])

[[0.21901136 0.90932002]
 [0.23502396 0.70220583]]


In [29]:
e[1, 1:] = 1
print(e)

[[0.1311735  0.21901136 0.90932002]
 [0.57748489 1.         1.        ]]


In [38]:
z = np.zeros((3,3), dtype = np.int64)
print(z)
z[1,:]= 3
z[:,-1]= 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [39]:
print(z.dtype)

int64


In [41]:
# Mathematical OPeratiom 
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])
print(x+y)
print(np.add(x,y))

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]


In [42]:
print(x-y)
print(np.subtract(x,y))

[[-3 -3]
 [-3 -3]]
[[-3 -3]
 [-3 -3]]


In [44]:
print(x*y)
print(np.multiply(x,y))

[[ 4 10]
 [18 28]]
[[ 4 10]
 [18 28]]


In [46]:
print(x/y)
print(np.divide(x,y))

[[0.25       0.4       ]
 [0.5        0.57142857]]
[[0.25       0.4       ]
 [0.5        0.57142857]]


In [47]:
print(x**0.5)
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [48]:
# Matrix Multiplication or Dot Product 
print(x.dot(y))
print(np.dot(x,y))

[[16 19]
 [36 43]]
[[16 19]
 [36 43]]


In [49]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [50]:
print(a)
print(sum(a))
print(max(a))

[1 2 3 4]
10
4


In [51]:
print(x)

[[1 2]
 [3 4]]


In [53]:
print(np.sum(x))

10


In [55]:
print(np.sum(x, axis = 0))

[4 6]


In [58]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [62]:
a= np.stack((a,b), axis = 0)
# print(np.stack((a,b),axis = 1))

ValueError: all input arrays must have the same shape

In [63]:
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]


In [78]:
a = a.reshape((-1,1))

In [79]:
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [16]
 [36]
 [64]]


In [80]:
c = np.random.random((2,3))

In [81]:
print(c)

[[0.44073528 0.01181787 0.58016226]
 [0.12889604 0.25829962 0.31563829]]


In [91]:
a = np.arange(10) +5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [94]:
np.random.shuffle(a)

In [95]:
print(a)

[ 7 14  6 13 12 11  9  5  8 10]


In [102]:
# Returns values from random normal distribution
a = np.random.randn(2,3)
print(a)

[[-0.11058748  0.3873377   1.57600733]
 [ 0.72036542 -0.42368207 -0.57524999]]


In [4]:
import numpy as np
a = np.arange(10)

In [5]:
print(np)

<module 'numpy' from 'C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>


In [6]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[26 33 98 83 92]


In [20]:
a = np.random.randn(2,3)

In [21]:
print(a)

[[ 0.75140076  3.02544682  0.79629104]
 [ 1.39387591  1.09690897 -0.3157876 ]]


In [23]:
a = np.random.randint(10, 100, 5)

In [24]:
print(a)

[83 33 26 92 98]


In [47]:
 element = np.random.choice(a)

In [48]:
print(element)

92


In [69]:
import numpy as np

# Set the random seed
np.random.seed(1)

# Generate some random numbers
random_numbers = np.random.randn(5)

# Display the random numbers
print(random_numbers)


[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]


In [7]:
s = "geeksforgeeks"
counter = Counter(s)
print(counter)

ImportError: cannot import name 'counter' from 'collections' (C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\collections\__init__.py)

In [8]:
!pip install collections

ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections


In [10]:
collections?

Object `collections` not found.


In [11]:
from collections import Counter

In [12]:
s = "geeksforgeeks"
counter = Counter(s)
print(counter)

Counter({'e': 4, 'g': 2, 'k': 2, 's': 2, 'f': 1, 'o': 1, 'r': 1})


In [14]:
import collections

In [20]:
import time 
p =(time.strftime('%X'))
time.strptime?

Docstring:
strptime(string, format) -> struct_time

Parse a string to a time tuple according to a format specification.
See the library reference manual for formatting codes (same as
strftime()).

Commonly used format codes:

%Y  Year with century as a decimal number.
%m  Month as a decimal number [01,12].
%d  Day of the month as a decimal number [01,31].
%H  Hour (24-hour clock) as a decimal number [00,23].
%M  Minute as a decimal number [00,59].
%S  Second as a decimal number [00,61].
%z  Time zone offset from UTC.
%a  Locale's abbreviated weekday name.
%A  Locale's full weekday name.
%b  Locale's abbreviated month name.
%B  Locale's full month name.
%c  Locale's appropriate date and time representation.
%I  Hour (12-hour clock) as a decimal number [01,12].
%p  Locale's equivalent of either AM or PM.

Other codes may be available on your platform.  See documentation for
the C library strftime function.
Type:      builtin_function_or_method

In [21]:
import requests

In [22]:
url = "https://aiplex.lol/0:/CAT%20Intensive%20Online(All%20Exam)/CAT%202023/"

In [23]:
import bs4 from beautifulsoup

SyntaxError: Did you mean to use 'from ... import ...' instead? (1226039509.py, line 1)

In [24]:
from beautifulsoup import bs4

ModuleNotFoundError: No module named 'beautifulsoup'

In [25]:
from bs4 import BeautifulSoup

In [26]:
soup = BeautifulSoup(url.content)

AttributeError: 'str' object has no attribute 'content'

In [31]:
url= "https://aiplex.lol/"

In [32]:
import requests
from requests.exceptions import Timeout

try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()  # Raise an HTTPError for bad responses
    # Process the response here
except Timeout:
    print("The request timed out")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")


An error occurred: 403 Client Error: Forbidden for url: https://aiplex.lol/


In [29]:
print(response)

<Response [403]>


In [39]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [40]:
print(np.min(a))

1


# Specify axis for direction in case of multi dimesion 

In [41]:
print(np.min(a, axis = 0))

[1 2 3]


In [42]:
print(np.min(a, axis = 1))

[1 4]


# Mean and average of all the elements 

In [45]:
b = np.array([1,2,3,4,5])
print(sum(b)/5)
print(np.mean(b))

3.0
3.0


In [46]:
print(np.mean(a, axis = 0)) #Mean of all the column 

[2.5 3.5 4.5]


In [47]:
print(np.mean(a, axis = 1)) #Mean along all the rows 

[2. 5.]


# Median of all the elements 

In [55]:
a = np.array([4,3,2,0,1,5])

In [56]:
print(np.median(a))

2.5


# Difference between mean and average

In [59]:
wt = np.array([1,2,3,4,5,6])
print(a.shape)
print(np.average(a, weights = wt))

(6,)
2.4285714285714284


# Standard Deviation

In [61]:
# using the formula
u = np.mean(a)
sm = np.sqrt(np.mean(abs(a-u)**2))
print(sm)

1.707825127659933


In [62]:
# Inbuilt function 
st = np.std(a)
print(st)

1.707825127659933


# Variance

In [63]:
print(sm**2)
print(np.var(a))

2.9166666666666665
2.9166666666666665
